language: node_js
sudo: false
node_js:
- '0.12'
script:
- git config --global user.email "deploy-script@travis-ci.org"
- git config --global user.name "Nathan Friedly [via Travis CI]"
- npm run deploy
env:
  global:
    # GH_KEY env variable with a "personal access token" - https://github.com/settings/tokens
    secure: J6aak8ciCjiJ/rBP9If3CzKzPwyHoZbZKuMtQJcOr5UkAm6EqydpvHPv63RvQlit8XXE6if2v7pdy7Mxy9ZXvE3/D7nwbOkiQ5PaX/Rh1v7GVb7160fYUqUNkgCdMNHEcQ0Yqgr/z6lrzIW618hbgvr1rUPoiK093MuOOoiEz7M=
